name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-latest
                      platform: windows

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Install system dependencies
              if: ${{ matrix.platform == 'linux' }}
              run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Run Electron Builder
              run: |
                  bun run electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
